### ISSUE TITLE
Feedback for HW #15

### ISSUE THREAD

**Issue by Scorpio750** [evanbates/classApp#1]
- Sequelize configuration did not initially build
- App does not serve (localhost:8080 returns empty response)

**Comment by evanbates** [comment]
Was working fine at time of submission, who knows what dependencies may have changed in the last three months since it was submitted? It would be helpful if you would grade these closer to the time of submission. Also it runs on PORT 8080 not 8000.

**Comment by Scorpio750** [comment]
Okay, here is the updated feedback:
- App does not redirect upon loading initial state
- No responsive feedback for success/failure of login/signup
- Teacher sign-in takes me back to login page, but TA sign-in takes me to populated list of (dummy?) teachers/TAs
- UI is very confusing to navigate

**Comment by evanbates** [comment]
ok, fair enough
